In [1]:
#Dictionary with single key-value pair
person = {
    "First_Name" : "Aditi",
    "Last_Name" : "Shaktawat",
    "Email" : "abc@email.com"
}

In [2]:
#Dictionary with multiple values in key using list
person = {
    "First_Name" : ["Aditi", "Joe", "Anu"],
    "Last_Name" : ["Shaktawat", "Sin", "Dat"],
    "Email" : ["abc@email.com", "av@email.com", "fgees@email.com"]
}

In [3]:
person['Email']

['abc@email.com', 'av@email.com', 'fgees@email.com']

Creating a dataframe

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(person)

In [6]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

Series - Return single column

In [7]:
#Accesing a singlr column in dataframe
df.Email 
#OR 
df['Email']

0      abc@email.com
1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [8]:
#Accesing Multiple columns - dataframe
df[['First_Name', 'Email']]

  First_Name            Email
0      Aditi    abc@email.com
1        Joe     av@email.com
2        Anu  fgees@email.com

In [9]:
#Return all columns
df.columns

Index(['First_Name', 'Last_Name', 'Email'], dtype='object')

Selecting Rows

In [10]:
#Return all rows
# 1. Using iloc- integer location
df.iloc[[0,1]]

  First_Name  Last_Name          Email
0      Aditi  Shaktawat  abc@email.com
1        Joe        Sin   av@email.com

In [11]:
df.iloc[[1,2],2]  #Return 2nd column rows with index 1,2

1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [12]:
#2. Using loc - search by labels
df.loc[[1,2], ['Email', 'First_Name']]

             Email First_Name
1     av@email.com        Joe
2  fgees@email.com        Anu

Indexing

In [13]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

In [18]:
#to set 'email' column as index
df.set_index( 'Email',inplace=True)

In [19]:
df

                First_Name  Last_Name
Email
abc@email.com        Aditi  Shaktawat
av@email.com           Joe        Sin
fgees@email.com        Anu        Dat

In [22]:
#Finding rows using 'email' as label
df.loc[ 'av@email.com']

First_Name    Joe
Last_Name     Sin
Name: av@email.com, dtype: object

In [24]:
#  df.loc[0]   --will give error as int labels no longer acting as labels

In [ ]:
# return a specific column for the speciified row
df.loc['av@email.com','First_Name']

'Joe'

In [27]:
#Reset index
df.reset_index(inplace=True)
df

   index            Email First_Name  Last_Name
0      0    abc@email.com      Aditi  Shaktawat
1      1     av@email.com        Joe        Sin
2      2  fgees@email.com        Anu        Dat

Filtering

In [40]:
#1st way
filt = df['Last_Name'] == 'Shaktawat'   #Returns a series of true false booleans

In [ ]:
# df[filt]
# or
# df.loc[filt]

   index          Email First_Name  Last_Name
0      0  abc@email.com      Aditi  Shaktawat

In [ ]:
df.loc[filt, 'Email']   #return email where last name is 'Shaktawat'

0    abc@email.com
Name: Email, dtype: object

In [46]:
# 2nd way
df[df['Last_Name'] == 'Shaktawat']

   index          Email First_Name  Last_Name
0      0  abc@email.com      Aditi  Shaktawat

In [52]:
# AND filter
df[(df['First_Name'] == 'Aditi') & (df['Email'] == 'abc@email.com')]

   index          Email First_Name  Last_Name
0      0  abc@email.com      Aditi  Shaktawat

In [49]:
filt = (df['Last_Name'] == 'Shaktawat') & (df['Email'] == 'abc@email.com')
df.loc[filt]

   index          Email First_Name  Last_Name
0      0  abc@email.com      Aditi  Shaktawat

In [ ]:
# OR condition
df[(df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')]

   index          Email First_Name  Last_Name
0      0  abc@email.com      Aditi  Shaktawat
1      1   av@email.com        Joe        Sin

In [58]:
filt = (df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')
df.loc[filt, 'First_Name']

0    Aditi
1      Joe
Name: First_Name, dtype: object

In [ ]:
# NOT 
df.loc[~filt]   #opposite of filtering condition

   index            Email First_Name Last_Name
2      2  fgees@email.com        Anu       Dat