In [ ]:
#Dictionary with single key-value pair
person = {
    "First_Name" : "Aditi",
    "Last_Name" : "Shaktawat",
    "Email" : "abc@email.com"
}

In [4]:
#Dictionary with multiple values in key using list
person = {
    "First_Name" : ["Aditi", "Joe", "Anu"],
    "Last_Name" : ["Shaktawat", "Sin", "Dat"],
    "Email" : ["abc@email.com", "av@email.com", "fgees@email.com"]
}

In [5]:
person['Email']

['abc@email.com', 'av@email.com', 'fgees@email.com']

Creating a dataframe

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(person)

In [8]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

Series - Return single column

In [ ]:
#Accesing a singlr column in dataframe
df.Email 
#OR 
df['Email']

0      abc@email.com
1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [14]:
#Accesing Multiple columns - dataframe
df[['First_Name', 'Email']]

  First_Name            Email
0      Aditi    abc@email.com
1        Joe     av@email.com
2        Anu  fgees@email.com

In [16]:
#Return all columns
df.columns

Index(['First_Name', 'Last_Name', 'Email'], dtype='object')

Selecting Rows

In [18]:
#Return all rows
# 1. Using iloc- integer location
df.iloc[[0,1]]

  First_Name  Last_Name          Email
0      Aditi  Shaktawat  abc@email.com
1        Joe        Sin   av@email.com

In [19]:
df.iloc[[1,2],2]  #Return 2nd column rows with index 1,2

1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [23]:
#2. Using loc - search by labels
df.loc[[1,2], ['Email', 'First_Name']]

             Email First_Name
1     av@email.com        Joe
2  fgees@email.com        Anu