In [220]:
#Dictionary with single key-value pair
person = {
    "First_Name" : "Aditi",
    "Last_Name" : "Shaktawat",
    "Email" : "abc@email.com"
}

In [221]:
#Dictionary with multiple values in key using list
person = {
    "First_Name" : ["Aditi", "Joe", "Anu"],
    "Last_Name" : ["Shaktawat", "Sin", "Dat"],
    "Email" : ["abc@email.com", "av@email.com", "fgees@email.com"]
}

In [222]:
person['Email']

['abc@email.com', 'av@email.com', 'fgees@email.com']

Creating a dataframe

In [223]:
import pandas as pd

In [224]:
df = pd.DataFrame(person)

In [225]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

Series - Return single column

In [226]:
#Accesing a singlr column in dataframe
df.Email 
#OR 
df['Email']

0      abc@email.com
1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [227]:
#Accesing Multiple columns - dataframe
df[['First_Name', 'Email']]

  First_Name            Email
0      Aditi    abc@email.com
1        Joe     av@email.com
2        Anu  fgees@email.com

In [228]:
#Return all columns
df.columns

Index(['First_Name', 'Last_Name', 'Email'], dtype='object')

Selecting Rows

In [229]:
#Return all rows
# 1. Using iloc- integer location
df.iloc[[0,1]]

  First_Name  Last_Name          Email
0      Aditi  Shaktawat  abc@email.com
1        Joe        Sin   av@email.com

In [230]:
df.iloc[[1,2],2]  #Return 2nd column rows with index 1,2

1       av@email.com
2    fgees@email.com
Name: Email, dtype: object

In [231]:
#2. Using loc - search by labels
df.loc[[1,2], ['Email', 'First_Name']]

             Email First_Name
1     av@email.com        Joe
2  fgees@email.com        Anu

Indexing

In [232]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [233]:
df

  First_Name  Last_Name            Email
0      Aditi  Shaktawat    abc@email.com
1        Joe        Sin     av@email.com
2        Anu        Dat  fgees@email.com

In [234]:
#to set 'email' column as index
df.set_index( 'Email',inplace=True)

In [235]:
df

                First_Name  Last_Name
Email
abc@email.com        Aditi  Shaktawat
av@email.com           Joe        Sin
fgees@email.com        Anu        Dat

In [236]:
#Finding rows using 'email' as label
df.loc[ 'av@email.com']

First_Name    Joe
Last_Name     Sin
Name: av@email.com, dtype: object

In [237]:
#  df.loc[0]   --will give error as int labels no longer acting as labels

In [238]:
# return a specific column for the speciified row
df.loc['av@email.com','First_Name']

'Joe'

In [239]:
#Reset index
df.reset_index(inplace=True)
df

             Email First_Name  Last_Name
0    abc@email.com      Aditi  Shaktawat
1     av@email.com        Joe        Sin
2  fgees@email.com        Anu        Dat

Filtering

In [240]:
#1st way
filt = df['Last_Name'] == 'Shaktawat'   #Returns a series of true false booleans

In [241]:
# df[filt]
# or
# df.loc[filt]

In [242]:
df.loc[filt, 'Email']   #return email where last name is 'Shaktawat'

0    abc@email.com
Name: Email, dtype: object

In [243]:
# 2nd way
df[df['Last_Name'] == 'Shaktawat']

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [244]:
# AND filter
df[(df['First_Name'] == 'Aditi') & (df['Email'] == 'abc@email.com')]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [245]:
filt = (df['Last_Name'] == 'Shaktawat') & (df['Email'] == 'abc@email.com')
df.loc[filt]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat

In [246]:
# OR condition
df[(df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')]

           Email First_Name  Last_Name
0  abc@email.com      Aditi  Shaktawat
1   av@email.com        Joe        Sin

In [247]:
filt = (df['Last_Name'] == 'Sin') | (df['Email'] == 'abc@email.com')
df.loc[filt, 'First_Name']

0    Aditi
1      Joe
Name: First_Name, dtype: object

In [248]:
# NOT 
df.loc[~filt]   #opposite of filtering condition

             Email First_Name Last_Name
2  fgees@email.com        Anu       Dat

Alteriing Columns

In [249]:
df.columns

Index(['Email', 'First_Name', 'Last_Name'], dtype='object')

In [250]:
# 1. changing column names using list
df.columns = ['First', 'Last', 'email']
df

             First   Last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [251]:
# 2. Renaming few column names - using dictionary
df.rename(columns= {'First' :'First Name', 'email' : 'Email'}, inplace= True)

In [252]:
df   # need to add inplace = true for rename

        First Name   Last      Email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [253]:
#Changing CASE of columns   - list comprehension
df.columns = [x.upper() for x in df.columns]
df

        FIRST NAME   LAST      EMAIL
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [254]:
df.columns = [x.lower() for x in df.columns]
df

        first name   last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

In [255]:
# replacing values/ spaces in columns
df.columns = df.columns.str.replace(' ', '_')
df

        first_name   last      email
0    abc@email.com  Aditi  Shaktawat
1     av@email.com    Joe        Sin
2  fgees@email.com    Anu        Dat

Updating Row values

In [256]:
df.loc[2]

first_name    fgees@email.com
last                      Anu
email                     Dat
Name: 2, dtype: object

In [ ]:
#updating Single value
# 1. directly updating all the values for a single row

df.loc[2] = ['Vin', 'Jain', 'vin@gmail.com']
df

      first_name   last          email
0  abc@email.com  Aditi      Shaktawat
1   av@email.com    Joe            Sin
2            Vin   Jain  vin@gmail.com

In [ ]:
# 2. Updating few particular values for a single row 
df.loc[2, ['first_name','email']] =[ 'Vinamra' , 'vinad@gmail.com']
df

      first_name   last            email
0  abc@email.com  Aditi        Shaktawat
1   av@email.com    Joe              Sin
2        Vinamra   Jain  vinad@gmail.com

In [260]:
# 3. update single value
df.loc[ 2, 'email'] = 'vinlovad@email.com'
df

      first_name   last               email
0  abc@email.com  Aditi           Shaktawat
1   av@email.com    Joe                 Sin
2        Vinamra   Jain  vinlovad@email.com

Updating multiple rows values

In [266]:
df['first_name'] = df['first_name'].str.lower()
df

      first_name   last               email
0  abc@email.com  Aditi           Shaktawat
1   av@email.com    Joe                 Sin
2        vinamra   Jain  vinlovad@email.com

APPLY

In [ ]:
# 1. APPLY with series - apply changes to each value of series

df['email'].apply(len)

0     9
1     3
2    18
Name: email, dtype: int64

In [274]:
#cretaing a func for converting the case of email
def email_upper(email):
    return email.upper()
df['email'].apply(email_upper)
#apply to the column
df['email'] = df['email'].apply(email_upper)

In [275]:
df

      first_name   last               email
0  abc@email.com  Aditi           SHAKTAWAT
1   av@email.com    Joe                 SIN
2        vinamra   Jain  VINLOVAD@EMAIL.COM

In [276]:
# Or using LAMBDA func
df['email'] = df['email'].apply(lambda x: x.lower())
df

      first_name   last               email
0  abc@email.com  Aditi           shaktawat
1   av@email.com    Joe                 sin
2        vinamra   Jain  vinlovad@email.com

In [ ]:
# 2. Apply with dataframe - apply func to every series in dataframe
df.apply(len)

first_name    3
last          3
email         3
dtype: int64

In [283]:
df.apply(pd.Series.max)

first_name               vinamra
last                         Joe
email         vinlovad@email.com
dtype: object

In [284]:
df.apply(lambda x: x.min())

first_name    abc@email.com
last                  Aditi
email             shaktawat
dtype: object

APPLY MAP

In [285]:
# Works in every individual value od dataframe
#does not work on series
df.applymap(len)

C:\Users\aditi\AppData\Local\Temp\ipykernel_22616\291979854.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(len)

   first_name  last  email
0          13     5      9
1          12     3      3
2           7     4     18

In [286]:
df.applymap(str.lower)

C:\Users\aditi\AppData\Local\Temp\ipykernel_22616\357608748.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(str.lower)

      first_name   last               email
0  abc@email.com  aditi           shaktawat
1   av@email.com    joe                 sin
2        vinamra   jain  vinlovad@email.com

MAP

In [ ]:
# works only on series
# use to substite each value in series with something else
df['first_name'].map({'aditi' : 'ad', 'vinamra' :'vin'})   # if value not changed, returns NAN

0    NaN
1    NaN
2    vin
Name: first_name, dtype: object

REPLACE

In [ ]:
#Wont return NAN for the values which are not changed
df['first_name']=df['first_name'].replace({'aditi' : 'ad', 'vinamra' :'vin'})
df

      first_name   last               email
0  abc@email.com  Aditi           shaktawat
1   av@email.com    Joe                 sin
2            vin   Jain  vinlovad@email.com